CRAWLS_DATA = [
    ("Benedict", "https://www.benedict.ch/stellen/", "08:00", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("Vantage", "https://www.vantage.ch/stellenportal/", "08:03", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("BZWU", "https://bzwu.ch/ueber-uns/info/stellenangebote/", "08:06", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("FFHS", "https://www.ffhs.ch/de/karriere", "08:09", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("FHGR", "https://jobs.fhgr.ch/Jobs/All?lang=ger", "08:12", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("Kanton St.Gallen", "https://recruitingapp-2800.umantis.com/Jobs/All?tc1152481=p1&_search_token1152481=2005273672#connectortable_1152481", "08:15", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("IPSO", "https://www.ipso.ch/karriere", "08:18", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("PHSG", "https://stellen-phsg.ch/", "08:21", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("OST", "https://ohws.prospective.ch/public/v1/medium/1007649/jobs?lang=de&offset=0&limit=999", "08:24", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("SwissEngineering", "https://www.swissengineering.ch/api/de/jobs", "08:27", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("Smartfeld", "https://startfeld.jobportal.jobchannel.ch/search", "08:30", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("Rheintal.com", "https://rheintalcom.jobportal.jobchannel.ch/search", "08:33", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("Digital Liechtenstein", "https://digitalliechtenstein.jobportal.jobchannel.ch/search", "08:36", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("EastDigital", "https://eastdigital.jobportal.jobchannel.ch/search", "08:39", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("Inside IT", "https://jobs.inside-it.ch/jobs/", "08:42", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("Abacus", "https://api.jobportal.abaservices.ch/api/application/publication/abacusjobs/0", "08:45", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("Stadt St.Gallen", "https://live.solique.ch/STSG/de/api/v1/data/", "08:48", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("Valantic", "https://www.valantic.com/de/karriere/", "08:51", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("Abraxas", "https://www.abraxas.ch/de/karriere/offene-stellen", "08:54", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("Bühler", "https://ohws.prospective.ch/public/v1/medium/1008005/jobs?lang=de&offset=0&limit=100&f=20:1708896", "08:57", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("Egeli Informatik", "https://jobs.dualoo.com/portal/lx0anfq4?lang=DE", "09:00", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("HOCH", "https://jobs.h-och.ch/search/?q=&sortColumn=referencedate&sortDirection=desc&startrow=000", "09:03", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("Inventex", "https://inventx.onlyfy.jobs/candidate/job/ajax_list?display_length=40&page=1&sort=alphabetic&sort_dir=ASC&_ps_widget_token=ns1QWluaGSXCkN7pU3DlaFAkwBC5JKxL6JrVZfe09kVZ2WTYwM8BUAK8JGk7-u56fMvnFKBlRtQ8Y84ZtbkG2wisV0sIHWpQ48vgF1GViXdwc8HmVjGXiIe5em11GzKpb7LWJ6Dl,cMUlABi5tzaIEuuFcn40IdmToom2DeLbGa,X6r1hKH1p8dbGWQtzzJYdJau7oOvsoF4EsYTI4LutGI9LsrMA5e1&parentUrl=https://www.inventx.ch/karriere/jobs/&widgetConfig=3763mqu8&_=1742828611375", "09:06", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("Infosystem", "https://www.infosystem.ch/karriere", "09:09", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("Hexagon / Geosystems", "https://hexagon.com/company/careers/job-listings#jl_country=Switzerland&jl_e=00", "09:12", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("Raiffeisen", "https://ohws.prospective.ch/public/v1/medium/1950/jobs?lang=de&offset=0&limit=300", "09:15", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("SFS", "https://join.sfs.com/ch/en/vacancies/index.jsp", "09:18", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("Umantis", "https://recruitingapp-9300.umantis.com/Jobs/All", "09:21", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("Acreo Consulting", "https://acreo.ch/unternehmen", "09:24", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("All Consulting", "https://all-consulting.ch/de/uber-uns/karriere/aktuelle-stellen", "09:27", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("Aproda", "https://www.aproda.ch/ueber-uns/karriere/offene-stellen", "09:30", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("Zoot Solutions", "https://www.zootsolutions.eu/de/career/", "09:33", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("StackWorks", "https://www.stackworks.ch/karriere#jobs", "09:36", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("Optisizer", "https://www.optisizer.ch/jobs", "09:39", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("ARI AG", "https://www.ari-ag.ch/jobs-karriere/offene-stellen/", "09:42", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("NextLevel Consulting", "https://www.nextlevelconsulting.com/karriere/#jobs", "09:45", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("Edorex", "https://edorex.ch/jobs/", "09:48", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("Diselva", "https://www.diselva.com/de/jobs", "09:51", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("APP", "https://app.ch/karriere/stellenangebote", "09:54", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("Advision", "https://advision.swiss/karriere/", "09:57", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("Xerxes", "https://www.xerxes.ch/stellen", "10:00", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("Webwirkung", "https://webwirkung.ch/karriere/", "10:03", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("stgallennetgroup", "https://stgallennetgroup.ch/unternehmen/jobs/", "10:06", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("Robotron", "https://www.robotron.ch/karriere", "10:09", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("JoshMartin", "https://joshmartin.ch/stellen/", "10:12", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("Farner", "https://www.farner.ch/de/jobs/", "10:15", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("Dynanet", "https://dynanet.ch/jobs/", "10:18", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("Dachcom", "https://www.dachcom.com/de-ch/agentur/karriere", "10:21", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("Adesso", "https://www.adesso.ch/de_ch/jobs-karriere/unsere-stellenangebote/stellenangebote.html", "10:24", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("Uni SG", "https://jobs.unisg.ch/?lang=de", "10:27", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("SVASG", "https://svasg-jobs.abacuscity.ch/de/jobportal/", "10:30", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("SGKB", "https://www.sgkb.ch/de/ueber-uns/karriere/stellenangebote", "10:33", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("SAK", "https://karriere.sak.ch/go/SAK-Jobs/9138055/", "10:36", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("Psychiatrie SG", "https://ohws.prospective.ch/public/v1/careercenter/1005765/?lang=de&limit=300", "10:39", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("Permapack", "https://jobs.dualoo.com/portal/ppqp7jqv?lang=DE", "10:42", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("Permapack Lehrstellen", "https://jobs.dualoo.com/portal/761twmr4?lang=DE", "10:45", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("Permapack Schnupperstellen", "https://jobs.dualoo.com/portal/4tgi9rpu?lang=DE", "10:48", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("Optimatik", "https://optimatik.ch/jobs", "10:51", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("Oertli", "https://oertli-jobs.com/stellenangebote.html", "10:54", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("OBT", "https://www.obt.ch/de/karriere/offene-stellen", "10:57", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("Netsafe", "https://www.netsafe.ch/jobs", "11:00", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("NeoVac", "https://www.neovac.ch/jobs", "11:03", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("MTF", "https://jobs.mtf.ch/de/jobportal", "11:06", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("MSDirect", "https://msdirectgroup-jobs.abacuscity.ch/de/jobportal", "11:09", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("Metrohm", "https://search-api.metrohm.com/search?seq=0&type=job&tag=jobs%3Acountries%2Fch&facet=true&rows=100&sort=date&searchPath=%2Fcontent%2Fmetrohm&lang=de&country=ch&start=0", "11:12", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("Merkle", "https://www.merkle.com/en/careers.jobs.js?offset=24&limit=400", "11:15", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("Kellenberger", "https://management.ostjob.ch/minisite/62", "11:18", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("Laveba", "https://jobs.dualoo.com/portal/elj8aw7v?lang=DE", "11:21", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("Emonitor", "https://join.com/companies/emonitor", "11:24", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("Xitrust", "https://www.xitrust.com/ch/ueber-uns/jobs/", "11:27", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("MAIT", "https://swiss-mait.career.softgarden.de/#jobs%3Alocation%253D%255B%2522St.%2520Gallen%2522%255D", "11:30", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
    ("Hostpoint", "https://www.hostpoint.ch/jobs/", "11:33", "Wed", ["praktikum", "praktika", "praktikant", "werkstudent", "student", "studium"]),
]