LOCALITIES_DATA = [
    ("Herisau", "AR"),
    ("Schachen b. Herisau", "AR"),
    ("Gossau SG", "AR"),
    ("Stein AR", "AR"),
    ("Hundwil", "AR"),
    ("Urnäsch", "AR"),
    ("Gonten", "AR"),
    ("Schönengrund", "AR"),
    ("Urnäsch", "AR"),
    ("Herisau", "AR"),
    ("Schwellbrunn", "AR"),
    ("Waldstatt", "AR"),
    ("Schönengrund", "AR"),
    ("Degersheim", "AR"),
    ("St. Gallen", "AR"),
    ("Stein AR", "AR"),
    ("Schwellbrunn", "AR"),
    ("Waldstatt", "AR"),
    ("Urnäsch", "AR"),
    ("Herisau", "AR"),
    ("Schwellbrunn", "AR"),
    ("Waldstatt", "AR"),
    ("Trogen", "AR"),
    ("Bühler", "AR"),
    ("Trogen", "AR"),
    ("Bühler", "AR"),
    ("Gais", "AR"),
    ("Altstätten SG", "AR"),
    ("Speicherschwendi", "AR"),
    ("Speicher", "AR"),
    ("St. Gallen", "AR"),
    ("Speicher", "AR"),
    ("Niederteufen", "AR"),
    ("Teufen AR", "AR"),
    ("Bühler", "AR"),
    ("Lustmühle", "AR"),
    ("Trogen", "AR"),
    ("Grub AR", "AR"),
    ("Rehetobel", "AR"),
    ("Grub SG", "AR"),
    ("Rehetobel", "AR"),
    ("Heiden", "AR"),
    ("Oberegg", "AR"),
    ("Wolfhalden", "AR"),
    ("Wienacht-Tobel", "AR"),
    ("Lutzenberg", "AR"),
    ("Wolfhalden", "AR"),
    ("Eggersriet", "AR"),
    ("Speicherschwendi", "AR"),
    ("Rehetobel", "AR"),
    ("Reute AR", "AR"),
    ("Schachen b. Reute", "AR"),
    ("Marbach SG", "AR"),
    ("Trogen", "AR"),
    ("Wald AR", "AR"),
    ("Wolfhalden", "AR"),
    ("Walzenhausen", "AR"),
    ("Heiden", "AR"),
    ("Thal", "AR"),
    ("Wolfhalden", "AR"),
    ("Walzenhausen", "AR"),
    ("Appenzell", "AI"),
    ("Appenzell Meistersrüte", "AI"),
    ("Appenzell Schlatt", "AI"),
    ("Gais", "AI"),
    ("Appenzell", "AI"),
    ("Gonten", "AI"),
    ("Gontenbad", "AI"),
    ("Jakobsbad", "AI"),
    ("Appenzell", "AI"),
    ("Appenzell Enggenhütten", "AI"),
    ("Appenzell Schlatt", "AI"),
    ("Niederteufen", "AI"),
    ("Teufen AR", "AI"),
    ("Haslen AI", "AI"),
    ("Bühler", "AI"),
    ("Gais", "AI"),
    ("Gonten", "AI"),
    ("Oberegg", "AI"),
    ("Oberegg", "AI"),
    ("Wolfhalden", "AI"),
    ("Walzenhausen", "AI"),
    ("Berneck", "AI"),
    ("Büriswilen", "AI"),
    ("Lüchingen", "AI"),
    ("Appenzell", "AI"),
    ("Appenzell Eggerstanden", "AI"),
    ("Appenzell Meistersrüte", "AI"),
    ("Appenzell Steinegg", "AI"),
    ("Weissbad", "AI"),
    ("Schwende", "AI"),
    ("Wasserauen", "AI"),
    ("Brülisau", "AI"),
    ("Urnäsch", "AI"),
    ("Gonten", "AI"),
    ("Frümsen", "AI"),
    ("Lömmenschwil", "SG"),
    ("Häggenschwil", "SG"),
    ("Winden", "SG"),
    ("Hagenwil b. Amriswil", "SG"),
    ("Bischofszell", "SG"),
    ("Lömmenschwil", "SG"),
    ("Muolen", "SG"),
    ("St. Gallen", "SG"),
    ("St. Gallen", "SG"),
    ("St. Gallen", "SG"),
    ("St. Gallen", "SG"),
    ("St. Gallen", "SG"),
    ("St. Gallen", "SG"),
    ("St. Gallen", "SG"),
    ("St. Gallen", "SG"),
    ("St.Gallen", "SG"),
    ("Sankt Gallen", "SG"),
    ("Abtwil SG", "SG"),
    ("Speicherschwendi", "SG"),
    ("Speicher", "SG"),
    ("Wittenbach", "SG"),
    ("St. Gallen", "SG"),
    ("Wittenbach", "SG"),
    ("Lömmenschwil", "SG"),
    ("Wittenbach", "SG"),
    ("Berg SG", "SG"),
    ("Freidorf TG", "SG"),
    ("Eggersriet", "SG"),
    ("Grub AR", "SG"),
    ("Grub SG", "SG"),
    ("Speicherschwendi", "SG"),
    ("Wienacht-Tobel", "SG"),
    ("Rorschach", "SG"),
    ("Goldach", "SG"),
    ("Tübach", "SG"),
    ("Mörschwil", "SG"),
    ("Rorschach", "SG"),
    ("Rorschacherberg", "SG"),
    ("Wienacht-Tobel", "SG"),
    ("Staad SG", "SG"),
    ("Berg SG", "SG"),
    ("Steinach", "SG"),
    ("Horn", "SG"),
    ("Tübach", "SG"),
    ("Untereggen", "SG"),
    ("Rorschacherberg", "SG"),
    ("Au SG", "SG"),
    ("Heerbrugg", "SG"),
    ("Heerbrugg", "SG"),
    ("Balgach", "SG"),
    ("Rebstein", "SG"),
    ("Reute AR", "SG"),
    ("Au SG", "SG"),
    ("Heerbrugg", "SG"),
    ("Berneck", "SG"),
    ("Büriswilen", "SG"),
    ("Balgach", "SG"),
    ("Widnau", "SG"),
    ("Diepoldsau", "SG"),
    ("Rheineck", "SG"),
    ("Thal", "SG"),
    ("Lutzenberg", "SG"),
    ("Rheineck", "SG"),
    ("Walzenhausen", "SG"),
    ("St. Margrethen SG", "SG"),
    ("Rorschacherberg", "SG"),
    ("Staad SG", "SG"),
    ("Altenrhein", "SG"),
    ("Thal", "SG"),
    ("Heerbrugg", "SG"),
    ("Widnau", "SG"),
    ("Brülisau", "SG"),
    ("Altstätten SG", "SG"),
    ("Lüchingen", "SG"),
    ("Hinterforst", "SG"),
    ("Eichberg", "SG"),
    ("Oberriet SG", "SG"),
    ("Rüthi (Rheintal)", "SG"),
    ("Lienz", "SG"),
    ("Hinterforst", "SG"),
    ("Eichberg", "SG"),
    ("Marbach SG", "SG"),
    ("Balgach", "SG"),
    ("Kriessern", "SG"),
    ("Montlingen", "SG"),
    ("Oberriet SG", "SG"),
    ("Marbach SG", "SG"),
    ("Rebstein", "SG"),
    ("Oberriet SG", "SG"),
    ("Rüthi (Rheintal)", "SG"),
    ("Lienz", "SG"),
    ("Haag (Rheintal)", "SG"),
    ("Buchs SG", "SG"),
    ("Gams", "SG"),
    ("Wildhaus", "SG"),
    ("Haag (Rheintal)", "SG"),
    ("Buchs SG", "SG"),
    ("Werdenberg", "SG"),
    ("Grabs", "SG"),
    ("Grabserberg", "SG"),
    ("Wildhaus", "SG"),
    ("Salez", "SG"),
    ("Sennwald", "SG"),
    ("Frümsen", "SG"),
    ("Sax", "SG"),
    ("Haag (Rheintal)", "SG"),
    ("Gams", "SG"),
    ("Buchs SG", "SG"),
    ("Sevelen", "SG"),
    ("Weite", "SG"),
    ("Sargans", "SG"),
    ("Weite", "SG"),
    ("Fontnas", "SG"),
    ("Trübbach", "SG"),
    ("Azmoos", "SG"),
    ("Oberschan", "SG"),
    ("Malans SG", "SG"),
    ("Gretschins", "SG"),
    ("Bad Ragaz", "SG"),
    ("Valens", "SG"),
    ("Heiligkreuz (Mels)", "SG"),
    ("Flums", "SG"),
    ("Berschis", "SG"),
    ("Flums Hochwiese", "SG"),
    ("Flumserberg Saxli", "SG"),
    ("Flumserberg Portels", "SG"),
    ("Flumserberg Bergheim", "SG"),
    ("Flumserberg Tannenheim", "SG"),
    ("Flumserberg Tannenbodenalp", "SG"),
    ("Schwendi im Weisstannental", "SG"),
    ("Weisstannen", "SG"),
    ("Mädris-Vermol", "SG"),
    ("Mels", "SG"),
    ("Heiligkreuz (Mels)", "SG"),
    ("Plons", "SG"),
    ("Pfäfers", "SG"),
    ("St. Margrethenberg", "SG"),
    ("Vadura", "SG"),
    ("Vättis", "SG"),
    ("Valens", "SG"),
    ("Vasön", "SG"),
    ("Murg", "SG"),
    ("Quinten", "SG"),
    ("Unterterzen", "SG"),
    ("Quarten", "SG"),
    ("Oberterzen", "SG"),
    ("Mols", "SG"),
    ("Flumserberg Bergheim", "SG"),
    ("Flumserberg Tannenbodenalp", "SG"),
    ("Sargans", "SG"),
    ("Heiligkreuz (Mels)", "SG"),
    ("Wangs", "SG"),
    ("Wangs", "SG"),
    ("Vilters", "SG"),
    ("Quinten", "SG"),
    ("Walenstadt", "SG"),
    ("Walenstadtberg", "SG"),
    ("Tscherlach", "SG"),
    ("Flums", "SG"),
    ("Berschis", "SG"),
    ("Flums Hochwiese", "SG"),
    ("Flumserberg Bergheim", "SG"),
    ("Weesen", "SG"),
    ("Amden", "SG"),
    ("Benken SG", "SG"),
    ("Buttikon SZ", "SG"),
    ("Benken SG", "SG"),
    ("Kaltbrunn", "SG"),
    ("Schänis", "SG"),
    ("Kaltbrunn", "SG"),
    ("Rufi", "SG"),
    ("Maseltrangen", "SG"),
    ("Ziegelbrücke", "SG"),
    ("Weesen", "SG"),
    ("Schmerikon", "SG"),
    ("Uznach", "SG"),
    ("Schmerikon", "SG"),
    ("Uznach", "SG"),
    ("Rüti ZH", "SG"),
    ("Wolfhausen", "SG"),
    ("Rapperswil SG", "SG"),
    ("Jona", "SG"),
    ("Wagen", "SG"),
    ("Feldbach", "SG"),
    ("Bollingen", "SG"),
    ("Ermenswil", "SG"),
    ("Ernetschwil", "SG"),
    ("Gebertingen", "SG"),
    ("Ricken SG", "SG"),
    ("Uznach", "SG"),
    ("Gommiswald", "SG"),
    ("Uetliburg SG", "SG"),
    ("Rieden SG", "SG"),
    ("Wald ZH", "SG"),
    ("Laupen ZH", "SG"),
    ("Goldingen", "SG"),
    ("Gebertingen", "SG"),
    ("Walde SG", "SG"),
    ("Neuhaus SG", "SG"),
    ("Eschenbach SG", "SG"),
    ("Ermenswil", "SG"),
    ("St. Gallenkappel", "SG"),
    ("Rüeterswil", "SG"),
    ("Hemberg", "SG"),
    ("Ebnat-Kappel", "SG"),
    ("Krummenau", "SG"),
    ("Urnäsch", "SG"),
    ("Alt St. Johann", "SG"),
    ("Unterwasser", "SG"),
    ("Wildhaus", "SG"),
    ("Urnäsch", "SG"),
    ("Hemberg", "SG"),
    ("Krummenau", "SG"),
    ("Nesslau", "SG"),
    ("Ennetbühl", "SG"),
    ("Neu St. Johann", "SG"),
    ("Stein SG", "SG"),
    ("Lichtensteig", "SG"),
    ("Ricken SG", "SG"),
    ("Dietfurt", "SG"),
    ("Lichtensteig", "SG"),
    ("Krinau", "SG"),
    ("Wattwil", "SG"),
    ("Ulisbach", "SG"),
    ("Hemberg", "SG"),
    ("Ebnat-Kappel", "SG"),
    ("Fischingen", "SG"),
    ("Wil SG", "SG"),
    ("Rickenbach b. Wil", "SG"),
    ("Kirchberg SG", "SG"),
    ("Dietschwil", "SG"),
    ("Gähwil", "SG"),
    ("Lütisburg Station", "SG"),
    ("Bazenheid", "SG"),
    ("Müselbach", "SG"),
    ("Mühlrüti", "SG"),
    ("Nassen", "SG"),
    ("Jonschwil", "SG"),
    ("Lütisburg Station", "SG"),
    ("Bazenheid", "SG"),
    ("Lütisburg", "SG"),
    ("Oberrindal", "SG"),
    ("Unterrindal", "SG"),
    ("Ganterschwil", "SG"),
    ("Au TG", "SG"),
    ("Steg im Tösstal", "SG"),
    ("Lütisburg Station", "SG"),
    ("Mosnang", "SG"),
    ("Dreien", "SG"),
    ("Mühlrüti", "SG"),
    ("Libingen", "SG"),
    ("Dietfurt", "SG"),
    ("Wattwil", "SG"),
    ("Lütisburg Station", "SG"),
    ("Bütschwil", "SG"),
    ("Ganterschwil", "SG"),
    ("Libingen", "SG"),
    ("Dietfurt", "SG"),
    ("Lichtensteig", "SG"),
    ("Oberhelfenschwil", "SG"),
    ("Schwellbrunn", "SG"),
    ("Schönengrund", "SG"),
    ("Urnäsch", "SG"),
    ("Degersheim", "SG"),
    ("Hoffeld", "SG"),
    ("Dicken", "SG"),
    ("Wolfertswil", "SG"),
    ("Mogelsberg", "SG"),
    ("Ebersol", "SG"),
    ("Nassen", "SG"),
    ("Brunnadern", "SG"),
    ("Necker", "SG"),
    ("St. Peterzell", "SG"),
    ("Lichtensteig", "SG"),
    ("Oberhelfenschwil", "SG"),
    ("Wattwil", "SG"),
    ("Hemberg", "SG"),
    ("Bächli (Hemberg)", "SG"),
    ("Degersheim", "SG"),
    ("Wolfertswil", "SG"),
    ("Flawil", "SG"),
    ("Degersheim", "SG"),
    ("Gossau SG", "SG"),
    ("Flawil", "SG"),
    ("Egg (Flawil)", "SG"),
    ("Oberuzwil", "SG"),
    ("Jonschwil", "SG"),
    ("Rickenbach b. Wil", "SG"),
    ("Schwarzenbach SG", "SG"),
    ("Oberrindal", "SG"),
    ("Flawil", "SG"),
    ("Niederglatt SG", "SG"),
    ("Oberuzwil", "SG"),
    ("Niederuzwil", "SG"),
    ("Bichwil", "SG"),
    ("Oberrindal", "SG"),
    ("Uzwil", "SG"),
    ("Oberuzwil", "SG"),
    ("Niederuzwil", "SG"),
    ("Henau", "SG"),
    ("Algetshausen", "SG"),
    ("Niederstetten", "SG"),
    ("Oberstetten", "SG"),
    ("Schwarzenbach SG", "SG"),
    ("Gossau SG", "SG"),
    ("Niederwil SG", "SG"),
    ("Niederbüren", "SG"),
    ("Schweizersholz", "SG"),
    ("Oberbüren", "SG"),
    ("Sonnental", "SG"),
    ("Zuzwil SG", "SG"),
    ("Lenggenwil", "SG"),
    ("Zuckenriet", "SG"),
    ("Niederhelfenschwil", "SG"),
    ("Niederwil SG", "SG"),
    ("Flawil", "SG"),
    ("Niederglatt SG", "SG"),
    ("Oberbüren", "SG"),
    ("Sonnental", "SG"),
    ("Wil SG", "SG"),
    ("Hosenruck", "SG"),
    ("Züberwangen", "SG"),
    ("Zuzwil SG", "SG"),
    ("Wil SG", "SG"),
    ("Rossrüti", "SG"),
    ("Wuppenau", "SG"),
    ("Zuzwil SG", "SG"),
    ("Schwarzenbach SG", "SG"),
    ("St. Margarethen TG", "SG"),
    ("Bronschhofen", "SG"),
    ("Andwil SG", "SG"),
    ("Arnegg", "SG"),
    ("Abtwil SG", "SG"),
    ("St. Josefen", "SG"),
    ("Engelburg", "SG"),
    ("Wittenbach", "SG"),
    ("St. Gallen", "SG"),
    ("Abtwil SG", "SG"),
    ("Herisau", "SG"),
    ("Gossau SG", "SG"),
    ("Andwil SG", "SG"),
    ("Arnegg", "SG"),
    ("Engelburg", "SG"),
    ("Andwil SG", "SG"),
    ("Waldkirch", "SG"),
    ("Hauptwil", "SG"),
    ("Niederbüren", "SG"),
    ("Wittenbach", "SG"),
    ("Bernhardzell", "SG"),
    ("Parpan", "GR"),
    ("Valbella", "GR"),
    ("Lenzerheide/Lai", "GR"),
    ("Vaz/Obervaz", "GR"),
    ("Tiefencastel", "GR"),
    ("Lantsch/Lenz", "GR"),
    ("Schmitten (Albula)", "GR"),
    ("Brienz/Brinzauls GR", "GR"),
    ("Tiefencastel", "GR"),
    ("Alvaschein", "GR"),
    ("Mon", "GR"),
    ("Stierva", "GR"),
    ("Surava", "GR"),
    ("Alvaneu Bad", "GR"),
    ("Alvaneu Dorf", "GR"),
    ("Cunter", "GR"),
    ("Tinizong", "GR"),
    ("Rona", "GR"),
    ("Mulegns", "GR"),
    ("Sur", "GR"),
    ("Marmorera", "GR"),
    ("Bivio", "GR"),
    ("Savognin", "GR"),
    ("Salouf", "GR"),
    ("Riom", "GR"),
    ("Riom", "GR"),
    ("Parsonz", "GR"),
    ("Filisur", "GR"),
    ("Bergün/Bravuogn", "GR"),
    ("Preda", "GR"),
    ("Stugl/Stuls", "GR"),
    ("Latsch", "GR"),
    ("Davos Wiesen", "GR"),
    ("Brusio", "GR"),
    ("Miralago", "GR"),
    ("Campocologno", "GR"),
    ("Viano", "GR"),
    ("Campascio", "GR"),
    ("Ospizio Bernina", "GR"),
    ("Alp Grüm", "GR"),
    ("S. Carlo (Poschiavo)", "GR"),
    ("Poschiavo", "GR"),
    ("Sfazù", "GR"),
    ("La Rösa", "GR"),
    ("Miralago", "GR"),
    ("Li Curt", "GR"),
    ("Le Prese", "GR"),
    ("Laax GR 2", "GR"),
    ("Falera", "GR"),
    ("Laax GR", "GR"),
    ("Laax GR 2", "GR"),
    ("Sagogn", "GR"),
    ("Schluein", "GR"),
    ("St. Martin (Lugnez)", "GR"),
    ("Vals", "GR"),
    ("Peiden", "GR"),
    ("Camuns", "GR"),
    ("Uors (Lumnezia)", "GR"),
    ("Surcasti", "GR"),
    ("Tersnaus", "GR"),
    ("Cumbel", "GR"),
    ("Morissen", "GR"),
    ("Vella", "GR"),
    ("Degen", "GR"),
    ("Vattiz", "GR"),
    ("Vignogn", "GR"),
    ("Lumbrein", "GR"),
    ("Vrin", "GR"),
    ("Pitasch", "GR"),
    ("Duvin", "GR"),
    ("Valendas", "GR"),
    ("Castrisch", "GR"),
    ("Sevgein", "GR"),
    ("Riein", "GR"),
    ("Ilanz", "GR"),
    ("Schnaus", "GR"),
    ("Schnaus", "GR"),
    ("Luven", "GR"),
    ("Ruschein", "GR"),
    ("Ladir", "GR"),
    ("Rueun", "GR"),
    ("Pigniu", "GR"),
    ("Siat", "GR"),
    ("Fürstenaubruck", "GR"),
    ("Fürstenau", "GR"),
    ("Rothenbrunnen", "GR"),
    ("Scharans", "GR"),
    ("Sils im Domleschg", "GR"),
    ("Rothenbrunnen", "GR"),
    ("Cazis", "GR"),
    ("Rodels", "GR"),
    ("Summaprada", "GR"),
    ("Tartar", "GR"),
    ("Sarn", "GR"),
    ("Portein", "GR"),
    ("Präz", "GR"),
    ("Dalin", "GR"),
    ("Flerden", "GR"),
    ("Flerden", "GR"),
    ("Summaprada", "GR"),
    ("Masein", "GR"),
    ("Thusis", "GR"),
    ("Mutten", "GR"),
    ("Obermutten", "GR"),
    ("Tschappina", "GR"),
    ("Urmein", "GR"),
    ("Versam", "GR"),
    ("Tenna", "GR"),
    ("Safien Platz", "GR"),
    ("Thalkirch", "GR"),
    ("Valendas", "GR"),
    ("Bonaduz", "GR"),
    ("Feldis/Veulden", "GR"),
    ("Trans", "GR"),
    ("Rodels", "GR"),
    ("Pratval", "GR"),
    ("Almens", "GR"),
    ("Paspels", "GR"),
    ("Tumegl/Tomils", "GR"),
    ("Scheid", "GR"),
    ("Avers", "GR"),
    ("Juf", "GR"),
    ("Sufers", "GR"),
    ("Andeer", "GR"),
    ("Clugin", "GR"),
    ("Pignia", "GR"),
    ("Rongellen", "GR"),
    ("Zillis", "GR"),
    ("Ausserferrera", "GR"),
    ("Innerferrera", "GR"),
    ("Innerferrera", "GR"),
    ("Splügen", "GR"),
    ("Medels im Rheinwald", "GR"),
    ("Nufenen", "GR"),
    ("Hinterrhein", "GR"),
    ("Donat", "GR"),
    ("Lohn GR", "GR"),
    ("Mathon", "GR"),
    ("Wergenstein", "GR"),
    ("Bonaduz", "GR"),
    ("Domat/Ems", "GR"),
    ("Rhäzüns", "GR"),
    ("Felsberg", "GR"),
    ("Flims Dorf", "GR"),
    ("Flims Waldhaus", "GR"),
    ("Fidaz", "GR"),
    ("Tamins", "GR"),
    ("Vättis", "GR"),
    ("Trin", "GR"),
    ("Tamins", "GR"),
    ("Trin Mulin", "GR"),
    ("Brail", "GR"),
    ("Zernez", "GR"),
    ("Susch", "GR"),
    ("Lavin", "GR"),
    ("Samnaun-Compatsch", "GR"),
    ("Samnaun Dorf", "GR"),
    ("Guarda", "GR"),
    ("Ardez", "GR"),
    ("Scuol", "GR"),
    ("Ftan", "GR"),
    ("Vulpera", "GR"),
    ("Tarasp", "GR"),
    ("Sent", "GR"),
    ("Vnà", "GR"),
    ("Ramosch", "GR"),
    ("Ramosch", "GR"),
    ("Vnà", "GR"),
    ("Strada", "GR"),
    ("Tschlin", "GR"),
    ("Martina", "GR"),
    ("Bever", "GR"),
    ("Bever", "GR"),
    ("St. Moritz", "GR"),
    ("Pontresina", "GR"),
    ("Celerina/Schlarigna", "GR"),
    ("Madulain", "GR"),
    ("Madulain", "GR"),
    ("Pontresina", "GR"),
    ("La Punt Chamues-ch", "GR"),
    ("Samedan", "GR"),
    ("Pontresina", "GR"),
    ("Silvaplana-Surlej", "GR"),
    ("St. Moritz", "GR"),
    ("Champfèr", "GR"),
    ("S-chanf", "GR"),
    ("Cinuos-chel", "GR"),
    ("Chapella", "GR"),
    ("Sils/Segl Maria", "GR"),
    ("Fex", "GR"),
    ("Sils/Segl Baselgia", "GR"),
    ("Plaun da Lej", "GR"),
    ("Champfèr", "GR"),
    ("Silvaplana", "GR"),
    ("Silvaplana-Surlej", "GR"),
    ("Zuoz", "GR"),
    ("Zuoz", "GR"),
    ("Avers", "GR"),
    ("Maloja", "GR"),
    ("Casaccia", "GR"),
    ("Vicosoprano", "GR"),
    ("Borgonovo", "GR"),
    ("Stampa", "GR"),
    ("Promontogno", "GR"),
    ("Bondo", "GR"),
    ("Castasegna", "GR"),
    ("Soglio", "GR"),
    ("Buseno", "GR"),
    ("Grono", "GR"),
    ("Castaneda", "GR"),
    ("Sta. Maria in Calanca", "GR"),
    ("Rossa", "GR"),
    ("Augio", "GR"),
    ("Sta. Domenica", "GR"),
    ("Sta. Maria in Calanca", "GR"),
    ("Lostallo", "GR"),
    ("Mesocco", "GR"),
    ("S. Bernardino", "GR"),
    ("Soazza", "GR"),
    ("Cama", "GR"),
    ("Grono", "GR"),
    ("Verdabbio", "GR"),
    ("Verdabbio", "GR"),
    ("Leggia", "GR"),
    ("Cama", "GR"),
    ("Roveredo GR", "GR"),
    ("Laura", "GR"),
    ("Lumino", "GR"),
    ("S. Vittore", "GR"),
    ("S. Vittore", "GR"),
    ("Arvigo", "GR"),
    ("Braggio", "GR"),
    ("Selma", "GR"),
    ("Cauco", "GR"),
    ("Tschierv", "GR"),
    ("Fuldera", "GR"),
    ("Lü", "GR"),
    ("Valchava", "GR"),
    ("Sta. Maria Val Müstair", "GR"),
    ("Müstair", "GR"),
    ("Davos Dorf", "GR"),
    ("Davos Wolfgang", "GR"),
    ("Davos Platz", "GR"),
    ("Davos Clavadel", "GR"),
    ("Davos Frauenkirch", "GR"),
    ("Davos Glaris", "GR"),
    ("Davos Monstein", "GR"),
    ("Davos Wiesen", "GR"),
    ("Fideris", "GR"),
    ("Furna", "GR"),
    ("Pragg-Jenaz", "GR"),
    ("Furna", "GR"),
    ("Jenaz", "GR"),
    ("Saas im Prättigau", "GR"),
    ("Serneus", "GR"),
    ("Klosters", "GR"),
    ("Klosters Dorf", "GR"),
    ("Davos Wolfgang", "GR"),
    ("Conters im Prättigau", "GR"),
    ("Küblis", "GR"),
    ("Lunden", "GR"),
    ("Buchen im Prättigau", "GR"),
    ("Putz", "GR"),
    ("Stels", "GR"),
    ("Küblis", "GR"),
    ("Luzein", "GR"),
    ("Pany", "GR"),
    ("Gadenstätt", "GR"),
    ("Ascharina", "GR"),
    ("St. Antönien", "GR"),
    ("Chur", "GR"),
    ("Haldenstein", "GR"),
    ("Maladers", "GR"),
    ("Malix", "GR"),
    ("Chur", "GR"),
    ("Passugg", "GR"),
    ("Malix", "GR"),
    ("Churwalden", "GR"),
    ("Parpan", "GR"),
    ("Castiel", "GR"),
    ("Lüen", "GR"),
    ("Calfreisen", "GR"),
    ("St. Peter", "GR"),
    ("Pagig", "GR"),
    ("Peist", "GR"),
    ("Arosa", "GR"),
    ("Molinis", "GR"),
    ("Langwies", "GR"),
    ("Litzirüti", "GR"),
    ("Davos Dorf", "GR"),
    ("Praden", "GR"),
    ("Tschiertschen", "GR"),
    ("Says", "GR"),
    ("Trimmis", "GR"),
    ("Valzeina", "GR"),
    ("Untervaz", "GR"),
    ("Zizers", "GR"),
    ("Landquart", "GR"),
    ("Maienfeld", "GR"),
    ("Fläsch", "GR"),
    ("Jenins", "GR"),
    ("Landquart", "GR"),
    ("Maienfeld", "GR"),
    ("Malans GR", "GR"),
    ("Untervaz", "GR"),
    ("Igis", "GR"),
    ("Landquart", "GR"),
    ("Mastrils", "GR"),
    ("St. Margrethenberg", "GR"),
    ("Valzeina", "GR"),
    ("Grüsch", "GR"),
    ("Fanas", "GR"),
    ("Grüsch", "GR"),
    ("Schiers", "GR"),
    ("Schiers", "GR"),
    ("Lunden", "GR"),
    ("Stels", "GR"),
    ("Stels", "GR"),
    ("Fajauna", "GR"),
    ("Schuders", "GR"),
    ("Pusserein", "GR"),
    ("Seewis Dorf", "GR"),
    ("Seewis-Pardisla", "GR"),
    ("Seewis-Schmitten", "GR"),
    ("Fanas", "GR"),
    ("Obersaxen", "GR"),
    ("Waltensburg/Vuorz", "GR"),
    ("Andiast", "GR"),
    ("Tavanasa", "GR"),
    ("Danis", "GR"),
    ("Dardin", "GR"),
    ("Breil/Brigels", "GR"),
    ("Disentis/Mustér", "GR"),
    ("Cavardiras", "GR"),
    ("Mumpé Medel", "GR"),
    ("Segnas", "GR"),
    ("Curaglia", "GR"),
    ("Platta", "GR"),
    ("Rabius", "GR"),
    ("Surrein", "GR"),
    ("S. Benedetg", "GR"),
    ("Sumvitg", "GR"),
    ("Cumpadials", "GR"),
    ("Disentis/Mustér", "GR"),
    ("Camischolas", "GR"),
    ("Sedrun", "GR"),
    ("Rueras", "GR"),
    ("Trun", "GR"),
    ("Zignau", "GR"),
    ("Schlans", "GR"),
    ("Rabius", "GR"),
    ("Obersaxen", "GR"),
    ("Flond", "GR"),
    ("Surcuolm", "GR"),
    ("Arbon", "TG"),
    ("Frasnacht", "TG"),
    ("Stachen", "TG"),
    ("Dozwil", "TG"),
    ("Steinebrunn", "TG"),
    ("Neukirch (Egnach)", "TG"),
    ("Winden", "TG"),
    ("Egnach", "TG"),
    ("Hefenhofen", "TG"),
    ("Horn", "TG"),
    ("Kesswil", "TG"),
    ("Freidorf TG", "TG"),
    ("Lömmenschwil", "TG"),
    ("Neukirch (Egnach)", "TG"),
    ("Frasnacht", "TG"),
    ("Stachen", "TG"),
    ("Roggwil TG", "TG"),
    ("Romanshorn", "TG"),
    ("Amriswil", "TG"),
    ("Salmsach", "TG"),
    ("Egnach", "TG"),
    ("Sommeri", "TG"),
    ("Romanshorn", "TG"),
    ("Uttwil", "TG"),
    ("Amriswil", "TG"),
    ("Hagenwil b. Amriswil", "TG"),
    ("Biessenhofen", "TG"),
    ("Schocherswil", "TG"),
    ("Oberaach", "TG"),
    ("Bischofszell", "TG"),
    ("Schweizersholz", "TG"),
    ("Halden", "TG"),
    ("Erlen", "TG"),
    ("Kümmertshausen", "TG"),
    ("Riedt b. Erlen", "TG"),
    ("Buchackern", "TG"),
    ("Engishofen", "TG"),
    ("Ennetaach", "TG"),
    ("Heldswil", "TG"),
    ("Hauptwil", "TG"),
    ("Bischofszell", "TG"),
    ("Wilen (Gottshaus)", "TG"),
    ("St. Pelagiberg", "TG"),
    ("Heldswil", "TG"),
    ("Hohentannen", "TG"),
    ("Kradolf", "TG"),
    ("Schönenberg an der Thur", "TG"),
    ("Buhwil", "TG"),
    ("Neukirch an der Thur", "TG"),
    ("Sulgen", "TG"),
    ("Götighofen", "TG"),
    ("Donzhausen", "TG"),
    ("Kradolf", "TG"),
    ("Zihlschlacht", "TG"),
    ("Sitterdorf", "TG"),
    ("Bischofszell", "TG"),
    ("Muolen", "TG"),
    ("Basadingen", "TG"),
    ("Schlattingen", "TG"),
    ("Unterstammheim", "TG"),
    ("Schlatt TG", "TG"),
    ("Diessenhofen", "TG"),
    ("Willisdorf", "TG"),
    ("Schlatt TG", "TG"),
    ("Aadorf", "TG"),
    ("Ettenhausen TG", "TG"),
    ("Guntershausen b. Aadorf", "TG"),
    ("Häuslenen", "TG"),
    ("Aawangen", "TG"),
    ("Wittenwil", "TG"),
    ("Frauenfeld", "TG"),
    ("Felben-Wellhausen", "TG"),
    ("Frauenfeld", "TG"),
    ("Gerlikon", "TG"),
    ("Matzingen", "TG"),
    ("Frauenfeld", "TG"),
    ("Islikon", "TG"),
    ("Kefikon TG", "TG"),
    ("Gachnang", "TG"),
    ("Harenwilen", "TG"),
    ("Mettendorf TG", "TG"),
    ("Hüttlingen", "TG"),
    ("Eschikofen", "TG"),
    ("Frauenfeld", "TG"),
    ("Matzingen", "TG"),
    ("Niederneunforn", "TG"),
    ("Wilen b. Neunforn", "TG"),
    ("Oberneunforn", "TG"),
    ("Stettfurt", "TG"),
    ("Matzingen", "TG"),
    ("Frauenfeld", "TG"),
    ("Thundorf", "TG"),
    ("Lustdorf", "TG"),
    ("Wetzikon TG", "TG"),
    ("Uesslingen", "TG"),
    ("Buch b. Frauenfeld", "TG"),
    ("Warth", "TG"),
    ("Weiningen TG", "TG"),
    ("Hüttwilen", "TG"),
    ("Altnau", "TG"),
    ("Kreuzlingen", "TG"),
    ("Bottighofen", "TG"),
    ("Ermatingen", "TG"),
    ("Triboltingen", "TG"),
    ("Gottlieben", "TG"),
    ("Güttingen", "TG"),
    ("Hugelshofen", "TG"),
    ("Neuwilen", "TG"),
    ("Dotnacht", "TG"),
    ("Ellighausen", "TG"),
    ("Lippoldswilen", "TG"),
    ("Siegershausen", "TG"),
    ("Alterswilen", "TG"),
    ("Altishausen", "TG"),
    ("Kreuzlingen", "TG"),
    ("Bottighofen", "TG"),
    ("Langrickenbach", "TG"),
    ("Zuben", "TG"),
    ("Schönenbaumgarten", "TG"),
    ("Herrenhof", "TG"),
    ("Kümmertshausen", "TG"),
    ("Illighausen", "TG"),
    ("Oberhofen TG", "TG"),
    ("Lengwil", "TG"),
    ("Lengwil", "TG"),
    ("Dettighofen (Lengwil)", "TG"),
    ("Scherzingen", "TG"),
    ("Münsterlingen", "TG"),
    ("Landschlacht", "TG"),
    ("Tägerwilen", "TG"),
    ("Kreuzlingen", "TG"),
    ("Raperswilen", "TG"),
    ("Hefenhausen", "TG"),
    ("Engwilen", "TG"),
    ("Sonterswil", "TG"),
    ("Wäldi", "TG"),
    ("Lipperswil", "TG"),
    ("Hattenhausen", "TG"),
    ("Gunterswilen", "TG"),
    ("Amlikon-Bissegg", "TG"),
    ("Tobel", "TG"),
    ("Affeltrangen", "TG"),
    ("Zezikon", "TG"),
    ("Märwil", "TG"),
    ("Buch b. Märwil", "TG"),
    ("Bettwiesen", "TG"),
    ("Balterswil", "TG"),
    ("Bichelsee", "TG"),
    ("Braunau", "TG"),
    ("Eschlikon TG", "TG"),
    ("Wallenwil", "TG"),
    ("Sirnach", "TG"),
    ("Wiezikon b. Sirnach", "TG"),
    ("Dussnang", "TG"),
    ("Oberwangen TG", "TG"),
    ("Fischingen", "TG"),
    ("Au TG", "TG"),
    ("Schmidrüti", "TG"),
    ("Sternenberg", "TG"),
    ("Lommis", "TG"),
    ("Weingarten-Kalthäusern", "TG"),
    ("Eschlikon TG", "TG"),
    ("Wil SG", "TG"),
    ("Münchwilen TG", "TG"),
    ("St. Margarethen TG", "TG"),
    ("Rickenbach b. Wil", "TG"),
    ("Wilen b. Wil", "TG"),
    ("Schwarzenbach SG", "TG"),
    ("Schönholzerswilen", "TG"),
    ("Sirnach", "TG"),
    ("Busswil TG", "TG"),
    ("Wiezikon b. Sirnach", "TG"),
    ("Littenheid", "TG"),
    ("Tägerschen", "TG"),
    ("Tobel", "TG"),
    ("Wängi", "TG"),
    ("Tuttwil", "TG"),
    ("Wilen b. Wil", "TG"),
    ("Wuppenau", "TG"),
    ("Hosenruck", "TG"),
    ("Berlingen", "TG"),
    ("Eschenz", "TG"),
    ("Lanzenneunforn", "TG"),
    ("Weiningen TG", "TG"),
    ("Herdern", "TG"),
    ("Hüttwilen", "TG"),
    ("Hörhausen", "TG"),
    ("Homburg", "TG"),
    ("Herdern", "TG"),
    ("Hüttwilen", "TG"),
    ("Nussbaumen TG", "TG"),
    ("Uerschhausen", "TG"),
    ("Eschenz", "TG"),
    ("Mammern", "TG"),
    ("Hörhausen", "TG"),
    ("Müllheim Dorf", "TG"),
    ("Pfyn", "TG"),
    ("Dettighofen", "TG"),
    ("Homburg", "TG"),
    ("Raperswilen", "TG"),
    ("Mannenbach-Salenstein", "TG"),
    ("Salenstein", "TG"),
    ("Fruthwilen", "TG"),
    ("Steckborn", "TG"),
    ("Kaltenbach", "TG"),
    ("Etzwilen", "TG"),
    ("Rheinklingen", "TG"),
    ("Wagenhausen", "TG"),
    ("Amlikon-Bissegg", "TG"),
    ("Bonau", "TG"),
    ("Weinfelden", "TG"),
    ("Berg TG", "TG"),
    ("Berg TG", "TG"),
    ("Andhausen", "TG"),
    ("Graltshausen", "TG"),
    ("Guntershausen b. Berg", "TG"),
    ("Mauren TG", "TG"),
    ("Opfershofen TG", "TG"),
    ("Mattwil", "TG"),
    ("Happerswil", "TG"),
    ("Birwinken", "TG"),
    ("Klarsreuti", "TG"),
    ("Andwil TG", "TG"),
    ("Buch b. Kümmertshausen", "TG"),
    ("Bürglen TG", "TG"),
    ("Istighofen", "TG"),
    ("Leimbach TG", "TG"),
    ("Opfershofen TG", "TG"),
    ("Bürglen TG", "TG"),
    ("Stehrenberg", "TG"),
    ("Lanterswil", "TG"),
    ("Friltschen", "TG"),
    ("Mettlen", "TG"),
    ("Märwil", "TG"),
    ("Bussnang", "TG"),
    ("Oberbussnang", "TG"),
    ("Oppikon", "TG"),
    ("Schmidshof", "TG"),
    ("Rothenhausen", "TG"),
    ("Märstetten", "TG"),
    ("Ottoberg", "TG"),
    ("Weinfelden", "TG"),
    ("Bürglen TG", "TG"),
    ("Müllheim-Wigoltingen", "TG"),
    ("Bonau", "TG"),
    ("Wigoltingen", "TG"),
    ("Engwang", "TG"),
    ("Illhart", "TG"),
    ("Lamperswil TG", "TG"),
    ("Märstetten", "TG"),
    ("Engwilen", "TG"),
    ("Wagerswil", "TG"),
    ("Gossau", "AR"),
    ("Stein", "AR"),
    ("Stein", "AR"),
    ("Altstätten", "AR"),
    ("Teufen", "AR"),
    ("Grub", "AR"),
    ("Grub", "AR"),
    ("Reute", "AR"),
    ("Marbach", "AR"),
    ("Wald", "AR"),
    ("Teufen", "AI"),
    ("Haslen", "AI"),
    ("Abtwil", "SG"),
    ("Berg", "SG"),
    ("Freidorf", "SG"),
    ("Grub", "SG"),
    ("Grub", "SG"),
    ("Staad", "SG"),
    ("Berg", "SG"),
    ("Au", "SG"),
    ("Reute", "SG"),
    ("Au", "SG"),
    ("St. Margrethen", "SG"),
    ("Staad", "SG"),
    ("Altstätten", "SG"),
    ("Oberriet", "SG"),
    ("Marbach", "SG"),
    ("Oberriet", "SG"),
    ("Marbach", "SG"),
    ("Oberriet", "SG"),
    ("Buchs", "SG"),
    ("Buchs", "SG"),
    ("Buchs", "SG"),
    ("Malans", "SG"),
    ("Benken", "SG"),
    ("Benken", "SG"),
    ("Rapperswil", "SG"),
    ("Ricken", "SG"),
    ("Uetliburg", "SG"),
    ("Rieden", "SG"),
    ("Walde", "SG"),
    ("Neuhaus", "SG"),
    ("Eschenbach", "SG"),
    ("Stein", "SG"),
    ("Ricken", "SG"),
    ("Wil", "SG"),
    ("Kirchberg", "SG"),
    ("Au", "SG"),
    ("Gossau", "SG"),
    ("Schwarzenbach", "SG"),
    ("Niederglatt", "SG"),
    ("Schwarzenbach", "SG"),
    ("Gossau", "SG"),
    ("Niederwil", "SG"),
    ("Zuzwil", "SG"),
    ("Niederwil", "SG"),
    ("Niederglatt", "SG"),
    ("Wil", "SG"),
    ("Zuzwil", "SG"),
    ("Wil", "SG"),
    ("Zuzwil", "SG"),
    ("Schwarzenbach", "SG"),
    ("St. Margarethen", "SG"),
    ("Andwil", "SG"),
    ("Abtwil", "SG"),
    ("Abtwil", "SG"),
    ("Gossau", "SG"),
    ("Andwil", "SG"),
    ("Andwil", "SG"),
    ("Brienz/Brinzauls", "GR"),
    ("Laax", "GR"),
    ("Lohn", "GR"),
    ("Roveredo", "GR"),
    ("Malans", "GR"),
    ("Freidorf", "TG"),
    ("Roggwil", "TG"),
    ("Schlatt", "TG"),
    ("Schlatt", "TG"),
    ("Ettenhausen", "TG"),
    ("Kefikon", "TG"),
    ("Mettendorf", "TG"),
    ("Wetzikon", "TG"),
    ("Weiningen", "TG"),
    ("Oberhofen", "TG"),
    ("Eschlikon", "TG"),
    ("Oberwangen", "TG"),
    ("Au", "TG"),
    ("Eschlikon", "TG"),
    ("Wil", "TG"),
    ("Münchwilen", "TG"),
    ("St. Margarethen", "TG"),
    ("Schwarzenbach", "TG"),
    ("Busswil", "TG"),
    ("Weiningen", "TG"),
    ("Nussbaumen", "TG"),
    ("Berg", "TG"),
    ("Berg", "TG"),
    ("Mauren", "TG"),
    ("Opfershofen", "TG"),
    ("Andwil", "TG"),
    ("Bürglen", "TG"),
    ("Leimbach", "TG"),
    ("Opfershofen", "TG"),
    ("Bürglen", "TG"),
    ("Bürglen", "TG"),
    ("Lamperswil", "TG"),
    ("Ruggell", "li"),
    ("Schellenberg", "li"),
    ("Gamprin", "li"),
    ("Eschen", "li"),
    ("Mauren", "li"),
    ("Schaan", "li"),
    ("Planken", "li"),
    ("Vaduz", "li"),
    ("Triesenberg", "li"),
    ("Triesen", "li"),
    ("Balzers", "li"),
    ("Rheintal", "SG"),
]